version: "3"

services:
  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

  app:
    build: ./
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"

volumes:
  dbdata:
